$(document).ready(function() { 
$( ".Menu" ).append( "<div class='sidebar-sticky'>"
            +"<ul class='nav flex-column'>"
              +"<li class='nav-item'>"
                +"<a class='nav-link active' href='#'>"
				 +" -Crear-"
                +"</a>"
              +"</li>"
              +"<li class='nav-item'>"
                +"<a class='nav-link' href='ProyectoGrid.php''>"
                  +"<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-file'>"+"<path d='M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z'>"+"</path>"+"<polyline points='13 2 13 9 20 9'>"+"</polyline>"+"</svg>"
                  +"Proyectos"
                +"</a>"
              +"</li>"
              +"<li class='nav-item'>"
                +"<a class='nav-link' href='RequerimientosGrid.php'>"
                  +"<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-shopping-cart'>"+"<circle cx='9' cy='21' r='1'>"+"</circle>"+"<circle cx='20' cy='21' r='1'>"+"</circle>"+"<path d='M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6'>"+"</path>"+"</svg>"
                 +" Requerimientos"
                +"</a>"
              +"</li>"
              +"<li class='nav-item'>"
                +"<a class='nav-link' href='#'>"
				  +"-Seguridad-"
                +"</a>"
              +"</li>"
              +"<li class='nav-item'>"
                +"<a class='nav-link' href='RolesGrid.php'>"
                  +"<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-bar-chart-2'>"+"<line x1='18' y1='20' x2='18' y2='10'>"+"</line>"+"<line x1='12' y1='20' x2='12' y2='4'>"+"</line>"+"<line x1='6' y1='20' x2='6' y2='14'>"+"</line>"+"</svg>"
                  +"Roles"
                +"</a>"
              +"</li>"
              +"<li class='nav-item'>"
               +"<a class='nav-link' href='#' id='roles'>"
                  +"-Usuario-"
                +"</a>"
              +"</li>"
			    +"<li class='nav-item'>"
                +"<a class='nav-link' href='ApruebaRequerimientoGrid.php'>"
                  +"<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-layers'>"+"<polygon points='12 2 2 7 12 12 22 7 12 2'>"+"</polygon>"+"<polyline points='2 17 12 22 22 17'>"+"</polyline>"+"<polyline points='2 12 12 17 22 12'>"+"</polyline>"+"</svg>"
                 +" Requerimientos"
                +"</a>"
              +"</li>"
			   +"<li class='nav-item'>"
               +"<a class='nav-link' href='#' id='roles'>"
                 +" -Reporte-"
                +"</a>"
              +"</li>"
			    +"<li class='nav-item' class='fe fe-user'>"
                +"<a class='nav-link' href='ReporteGrid.php'>"
                  +"Requerimientos"	
                +"</a>"
              +"</li>"
            +"</ul>"
        +"</nav>" );
 });